aws:
  region: ap-southeast-2
  availability_zone_a: ap-southeast-2a
  availability_zone_b: ap-southeast-2b

proxy:
  enabled: false
  protocol:
  host:
  port:

cron:
  env_path: '/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin'
  https_proxy:
