---

aws:
  region: ap-southeast-2
  availability_zone_list: ap-southeast-2a, ap-southeast-2b
  resources:
    stack_name: stack-builder-aem-resources
  cloudwatch:
    enable_log_subscription: false
    log_subscription_arn: overwrite-me
    enable_cloudwatch_cleanup: false

proxy:
  enabled: false
  protocol:
  host:
  port:
  user:
  password:
  noproxy:
    - localhost
    - 127.0.0.1

cron:
  env_path: /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin
  http_proxy:
  https_proxy:
  no_proxy:
