

network:
  stack_name: aem-network-stack

  internet_gateway:
    tag_name: AEM VPC Internet Gateway

  publish_dispatcher_elb:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher ELB Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher ELB Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher ELB Subnet C

  publish_dispatcher:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Publish Dispatcher Subnet C

  publish:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Publish Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Publish Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Publish Subnet C

  author:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Author Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Author Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Author Subnet C

  author_dispatcher:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Author Dispatcher Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Author Dispatcher Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Author Dispatcher Subnet C

  tool:
    ap-southeast-2a:
      cidr_block: overwrite-me
      tag_name: AEM Tool Subnet A
    ap-southeast-2b:
      cidr_block: overwrite-me
      tag_name: AEM Tool Subnet B
    ap-southeast-2c:
      cidr_block: overwrite-me
      tag_name: AEM Tool Subnet C

  public_route_table:
    tag_name: AEM VPC Public Route Table

  private_route_table:
    tag_name: AEM VPC Private Route Table

bastion:
  stack_name: aem-bastion-stack
  key_pair_name: overwrite-me
  ami_id: ami-ccecf5af
  subnet_id: overwrite-me
  security_groups: overwrite-me

#TODO: create a new elastic ip option?
nat_gateway:
  stack_name: aem-nat-gateway-stack
  elastic_ip_allocation_id: eipalloc-32711957

endpoints:
  s3: overwrite-me

network_exports:
  stack_name: aem-network-exports-stack
  VPCId: vpc-12345678
  AuthorPublishDispatcherSubnet: subnet-12345678
  PublishDispatcherELBSubnetList: subnet-12345678,subnet-87654321
  PublishDispatcherSubnetList: subnet-12345678,subnet-87654321
  PublishSubnetList: subnet-12345678,subnet-87654321
  AuthorPrimarySubnet: subnet-12345678
  AuthorStandbySubnet: subnet-87654321
  AuthorELBSubnetList: subnet-12345678,subnet-87654321
  AuthorDispatcherELBSubnetList: subnet-12345678,subnet-87654321
  AuthorDispatcherSubnetList: subnet-12345678,subnet-87654321
  ToolSubnetList: subnet-12345678,subnet-87654321
  PublicRouteTable: rtb-77cd4413
  PrivateRouteTable: rtb-75cd4411
