---
- name: AEM Author CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Get AEM Stack IAM Server Certificate
      iam_server_certificate_facts:
        name: "{{ compute.certificate_name }}"
      register: aem_stack_certificate
      tags:
      - create

    - name: Create AEM Author Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/author.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          SSLCertificateARNParameter: "{{ aem_stack_certificate.results[compute.certificate_name].arn }}"
          AuthorLoadBalancerHealthCheckTargetParameter: "{{ author.elb_health_check }}"
          AuthorSubnetAParameter: "{{ aem_vpc.author_subnet_a_id }}"
          AuthorSubnetBParameter: "{{ aem_vpc.author_subnet_b_id }}"
          AuthorInstanceProfileParameter: "{{ author.instance_profile }}"
          AuthorImageParameter: "{{ ami_ids.author }}"
          AuthorInstanceTypeParameter: "{{ author.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          AuthorRootVolSizeParameter: "{{ author.root_vol_size }}"
          AuthorDataVolSizeParameter: "{{ author.data_vol_size }}"
          AuthorTagNameParameter: "{{ stack_prefix }}-{{ author.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          AuthorLoadBalancerTagNameParameter: "{{ stack_prefix }}-{{ author.load_balancer.tag_name }}"
          RolesStackNameParameter: "{{ stack_prefix }}-{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ author.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ author.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Author Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
