---
- name: AEM Author CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Create AEM Author Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/author.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          NetworkStackPrefixParameter: "{{ network_stack_prefix }}"
          SSLCertificateARNParameter: "{{ compute.certificate_arn }}"
          AuthorLoadBalancerHealthCheckTargetParameter: "{{ author.elb_health_check }}"
          AuthorImageParameter: "{{ ami_ids.author }}"
          AuthorInstanceTypeParameter: "{{ author.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          AuthorRootVolSizeParameter: "{{ author.root_vol_size }}"
          AuthorDataVolSizeParameter: "{{ author.data_vol_size }}"
          UseAuthorDataVolSnapshotParameter: "{{ snapshots.author.use_data_vol_snapshot }}"
          AuthorDataVolSnapshotParamater: "{{ snapshots.author.data_vol_snapshot_id }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          AemAwsStackProvisionerVersionParameter: "{{ library.aem_aws_stack_provisioner_version }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ author.stack_name }}"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ author.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Author Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
