---
- name: AEM Author Dispatcher CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Create AEM Author Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/author-dispatcher.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          NetworkStackPrefixParameter: "{{ network_stack_prefix }}"
          SSLCertificateARNParameter: "{{ compute.certificate_arn }}"
          AuthorDispatcherLoadBalancerHealthCheckTargetParameter: "{{ author_dispatcher.elb_health_check }}"
          AuthorDispatcherImageParameter: "{{ ami_ids.author_dispatcher }}"
          AuthorDispatcherInstanceTypeParameter: "{{ author_dispatcher.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          AuthorDispatcherASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          AuthorDispatcherASGMaxSizeParameter: "{{ author_dispatcher.max_size }}"
          AuthorDispatcherASGMinSizeParameter: "{{ author_dispatcher.min_size }}"
          AuthorDispatcherRootVolSizeParameter: "{{ author_dispatcher.root_vol_size }}"
          AuthorDispatcherDataVolSizeParameter: "{{ author_dispatcher.data_vol_size }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
          AemAwsStackProvisionerVersionParameter: "{{ library.aem_aws_stack_provisioner_version }}"

      tags:
      - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ author_dispatcher.stack_name }}"
              --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ author_dispatcher.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Author Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ author_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
