---
- name: AEM App Stack Public Cert Creation
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM App Stack Public SSL Cert Used in CloudFront Distribution
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ cert_public.stack_name }}"
        region: us-east-1
        state: present
        template: "../../../cloudformation/apps/cert-public.yaml"
        template_parameters:
          MainStackPrefixParameter: "{{ stack_prefix }}"
          ApexDomainParameter: "{{ dns.apex_domain_name | regex_replace('(.*)\\.', '\\1') }}"
          StackSubdomainParameter: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}"
          BlueGreenSubdomainParameter: "{{ dns.blue_green_sub_domain }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ cert_public.stack_name}}"
             --query 'Stacks[].StackName' --region us-east-1
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ cert_public.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM App Stack Public SSL Cert
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ cert_public.stack_name }}"
        region: us-east-1
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
