---
- name: AEM Chaos Monkey CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Chaos Monkey Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/chaos-monkey.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          ChaosMonkeyInstanceProfileParameter: "{{ chaos_monkey.instance_profile }}"
          ChaosMonkeyImageParameter: "{{ ami_ids.chaos_monkey }}"
          ChaosMonkeyInstanceTypeParameter: "{{ chaos_monkey.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          ChaosMonkeyASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          ChaosMonkeyASGSubnetListParameter: "{{ aem_vpc.chaos_monkey_subnet_a_id }}, {{ aem_vpc.chaos_monkey_subnet_b_id }}"
          ChaosMonkeyRootVolSizeParameter: "{{ chaos_monkey.root_vol_size }}"
          ChaosMonkeyTagNameParameter: "{{ stack_prefix }}-{{ chaos_monkey.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          RolesStackNameParameter: "{{ stack_prefix }}-{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Chaos Monkey Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ chaos_monkey.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
