---
- name: AEM DNS Record Set CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create DNS Records CloudFormation Stack
      cloudformation:
        stack_name: "{{stack_prefix}}-{{ dns.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/dns-records.yaml"
        template_parameters:
          MainStackPrefixParameter: "{{ stack_prefix }}"
          Route53HostedZoneNameParameter: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name }}"
          AuthorDNSRecordSetNameParameter: "{{ dns.author.record_set_name }}"
          AuthorDispatcherDNSRecordSetNameParameter: "{{ dns.author_dispatcher.record_set_name }}"
          PublishDispatcherDNSRecordSetNameParameter: "{{ dns.publish_dispatcher.record_set_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
              aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ dns.stack_name }}"
                  --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ dns.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM DNS Record Set Stack
      cloudformation:
        stack_name: "{{stack_prefix}}-{{ dns.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
