---
- name: AEM Messaging CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Messaging Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ messaging.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/messaging.yaml"
        template_parameters:
          AEMASGEventQueueNameParameter: "{{ stack_prefix }}-{{ messaging.asg_event_sqs_queue_name }}"
          AEMASGEventTopicDisplayNameParameter: "{{ stack_prefix }} - {{ messaging.asg_event_sns_topic_display_name }}"
          AEMASGEventTopicNameParameter: "{{ stack_prefix }}-{{ messaging.asg_event_sns_topic_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ messaging.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ messaging.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Messaging Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ messaging.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"           
      tags:
      - delete
