---
- name: AEM Publish Dispatcher CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Get AEM Stack IAM Server Certificate
      iam_server_certificate_facts:
        name: "{{ compute.certificate_name }}"
      register: aem_stack_certificate
      tags:
      - create

    - name: Create AEM Publish Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/publish-dispatcher.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          SSLCertificateARNParameter: "{{ aem_stack_certificate.results[compute.certificate_name].arn }}"
          PublishDispatcherLoadBalancerHealthCheckTargetParameter: "{{ publish_dispatcher.elb_health_check }}"
          PublishDispatcherLoadBalancerSchemeParameter: "{{ publish_dispatcher.elb_scheme }}"
          PublishDispatcherELBSubnetAParameter: "{{ aem_vpc.publish_dispatcher_elb_subnet_a_id }}"
          PublishDispatcherELBSubnetBParameter: "{{ aem_vpc.publish_dispatcher_elb_subnet_b_id }}"
          PublishDispatcherInstanceProfileParameter: "{{ publish_dispatcher.instance_profile }}"
          PublishDispatcherImageParameter: "{{ ami_ids.publish_dispatcher }}"
          PublishDispatcherInstanceTypeParameter: "{{ publish_dispatcher.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          PublishDispatcherASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          PublishDispatcherASGSubnetListParameter: "{{ aem_vpc.publish_dispatcher_subnet_a_id }}, {{ aem_vpc.publish_dispatcher_subnet_b_id}}"
          PublishDispatcherASGMaxSizeParameter: "{{ publish_dispatcher.max_size }}"
          PublishDispatcherASGMinSizeParameter: "{{ publish_dispatcher.min_size }}"
          PublishDispatcherRootVolSizeParameter: "{{ publish_dispatcher.root_vol_size }}"
          PublishDispatcherDataVolSizeParameter: "{{ publish_dispatcher.data_vol_size }}"
          PublishDispatcherTagNameParameter: "{{ stack_prefix }}-{{ publish_dispatcher.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          PublishDispatcherLoadBalancerTagNameParameter: "{{ stack_prefix }}-{{ publish_dispatcher.load_balancer.tag_name }}"
          RolesStackNameParameter: "{{ stack_prefix }}-{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
          MessagingStackNameParameter: "{{ stack_prefix }}-{{ messaging.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Publish Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
