---
- name: AEM Roles CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Roles Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ roles.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/roles.yaml"
        template_parameters:
          PublishDispatcherRoleNameParameter: "{{ roles.publish_dispatcher }}"
          PublishRoleNameParameter: "{{ roles.publish }}"
          AuthorRoleNameParameter: "{{ roles.author }}"
          AuthorDispatcherRoleNameParameter: "{{ roles.author_dispatcher }}"
          OrchestratorRoleNameParameter: "{{ roles.orchestrator }}"
          ChaosMonkeyRoleNameParameter: "{{ roles.chaos_monkey }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ roles.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ roles.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Roles Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ roles.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"           
      tags:
      - delete
