---

- name: AEM Apps Prerequisite Resources Creation and Deletion Tasks
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    # - name: Create a Per Stack Route53 Hosted Zone
    #   route53_zone:
    #     zone: "{{ stack_prefix }}.{{dns.stack_sub_domain}}.{{ dns.apex_domain_name}}"
    #     comment: AEM {{ stack_prefix }} App Stacks Hosted Zone
    #     region: "{{ aws.region }}"
    #     state: present
    #   register: create_zone_result
    #   tags:
    #     - create
    #
    # - name: Retrieve the Hosted Zone ID of the Per Stack Zone
    #   route53_facts:
    #     query: hosted_zone
    #     hosted_zone_method: list_by_name
    #     dns_name: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name}}"
    #   register: list_zone_result
    #   tags:
    #     - create
    #     - delete
    #
    # - name: Retrieve Name Servers for per Stack Zone
    #   route53_facts:
    #     query: record_sets
    #     hosted_zone_id: "{{ list_zone_result.HostedZones[0].Id }}"
    #     type: NS
    #     start_record_name: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name}}"
    #     max_items: 1
    #   register: stack_zone_ns_records
    #   tags:
    #     - create
    #     - delete
    #
    # - name: Create a NS Record in Parenet Zone for the New Stack Zone
    #   route53:
    #     command: create
    #     record: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name}}"
    #     ttl: 86400
    #     type: NS
    #     zone: "{{ dns.apex_domain_name}}"
    #     value: "{{stack_zone_ns_records.ResourceRecordSets[0].ResourceRecords|json_query('[].Value')|sort|join(',')}}"
    #   tags:
    #     - create

    - name: Ensure data bucket exists
      s3_bucket:
        name: "{{ s3.data_bucket_name }}"
        state: present
      tags:
      - create

    - name: Upload CloudFormation Templates to S3
      command: >
              aws s3 sync ../../../../cloudformation/apps
                  s3://{{ s3.data_bucket_name }}/{{ stack_prefix }}
                  --include "*.yaml" --acl public-read
      tags:
        - create

    - name: Create AEM App Prerequisite Resources Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ prerequisites.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../../cloudformation/apps/full-set-2/prerequisites.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          NetworkStackPrefixParameter: "{{ network_stack_prefix }}"
          DataBucketNameParameter: "{{ s3.data_bucket_name }}"

          SecureShellInboundCidrIpParameter: "{{ security_groups.secure_shell.inbound_cidr_ip }}"
          PublishDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.publish_dispatcher_elb.inbound_cidr_ip }}"
          AuthorDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.author_dispatcher_elb.inbound_cidr_ip }}"
          PrivateSubnetInternetOutboundCidrIpParameter: "{{ security_groups.private_subnet_internet_outbound_cidr_ip }}"


      tags:
      - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ prerequisites.stack_name }}"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ prerequisites.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM App Prerequisite Resources Stacks
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ prerequisites.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete

    - name: Delete the NS Record in Parent Zone for the per Stack Zone
      route53:
        command: delete
        record:  "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name}}"
        ttl: 86400
        type: NS
        zone: "{{ dns.apex_domain_name}}"
        value: "{{stack_zone_ns_records.ResourceRecordSets[0].ResourceRecords|json_query('[].Value')|sort|join(',')}}"
      tags:
        - delete

    - name: Delete Per Stack Route53 Hosted Zone
      route53_zone:
        zone: "{{ stack_prefix }}.{{ dns.stack_sub_domain }}.{{ dns.apex_domain_name}}"
        region: "{{ aws.region }}"
        state: absent
      tags:
        - delete

    - name: Delete All Stack Data
      command: >
              aws s3 rm s3://"{{ s3.data_bucket_name }}"/"{{ stack_prefix }}"
               --recursive --region "{{ aws.region }}"
      tags:
      - delete
