---
- name: AEM Network CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  vars:
    az_array: "{{ aws.availability_zone_list.split(', ') }}"

  tasks:

    - name: Generate network resources playbook from jinja2 template
      template:
        src: "../../../templates/ansible/network-playbook.yaml.j2"
        dest: "./network-resources-generated.yaml"
      tags:
        - create

    - name: Create network CloudFormation template from jinja2 template
      template:
        src: "../../../templates/ansible/network-cf.yaml.j2"
        dest: "../../../../templates/cloudformation/network/network.yaml"
      tags:
        - create

    - name: Include generated network resources playbook tasks
      include_tasks: network-resources-generated.yaml
      tags:
        - create

    - name: Check if a Stack Exists
      command: >
       aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ network.stack_name }}"
            --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ network.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Network Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ network.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
        - delete
