---
- name: AEM Stack Data Tasks
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Create stage directory
      file:
        path: ../../../../stage/
        state: directory
      tags:
        - create

    - name: Create Stack Manager Cloud directory
      file:
        path: ../../../../stage/aem-stack-manager-cloud
        state: directory
      tags:
        - create

    - name: Check AEM Stack Manager artifact existence
      stat:
        path: ../../../../stage/aem-stack-manager-cloud.zip
      register: check_aem_stack_manager_cloud_result
      tags:
        - create

    - name: Download aem-stack-manager-cloud library
      aws_s3:
        bucket: "{{ s3.data_bucket_name }}"
        object: "library/aem-stack-manager-cloud-{{ library.aem_stack_manager_version }}.zip"
        dest: ../../../../stage/aem-stack-manager-cloud.zip
        mode: get
      when: check_aem_stack_manager_cloud_result.stat.exists == False
      tags:
        - create

    - name: Unpack aem-stack-manager-cloud library to stage directory
      unarchive:
        src: ../../../../stage/aem-stack-manager-cloud.zip
        dest: ../../../../stage/aem-stack-manager-cloud
      tags:
        - create

    - name: Package Lambda functions
      command: >
        zip -j "../../../../stage/{{ item }}.zip" "../../../../stage/aem-stack-manager-cloud/lambda/{{ item }}.py"
      with_items:
        - aem_stack_manager
        - aem_offline_snapshot
        - aem_task_query
        - purge_snapshots
      tags:
        - create

    - name: Upload Lambda functions
      aws_s3:
        bucket: "{{ s3.data_bucket_name }}"
        object: "{{stack_prefix }}/{{ stack_manager.s3_prefix }}/{{ item }}.zip"
        src: ../../../../stage/{{ item }}.zip
        mode: put
      with_items:
        - aem_stack_manager
        - aem_offline_snapshot
        - aem_task_query
        - purge_snapshots
      tags:
        - create

    - name: Delete AEM Stack Manager artifact
      ignore_errors: true
      file:
        path: ../../../../stage/aem-stack-manager-cloud.zip
        state: absent
      tags:
        - delete
        - create

    - name: Delete Lambda function packages
      ignore_errors: true
      file:
        path: ../../../../stage/{{ item }}.zip
        state: absent
      with_items:
        - aem_stack_manager
        - aem_offline_snapshot
        - aem_task_query
        - purge_snapshots
      tags:
        - delete
        - create
