---

- name: Create Stack Builder AEM AWS resources stack
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Create AWS Region file
      template:
        src: ../../../../templates/ansible/cloudformation.j2
        dest: ../../../../stage/awsregion.yaml
      tags:
        - create

    - name: AWS ELB Account ID
      include_vars:
        file: ../../../../stage/awsregion.yaml
        name: awselbaccountids
      tags:
        - create

    - name: Create AWS resources stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ aws.resources.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../../templates/cloudformation/apps/aws-resources.yaml"
        template_parameters:
          AWSELBAccountID: "{{ awselbaccountids.id }}"
          CreateS3Bucket: "{{ s3.create_bucket_flag }}"
          CreatePrivateHostedZone: "{{ dns_records.create_hosted_zone_flag }}"
          AemEnvS3BucketName: "{{ s3.data_bucket_name }}"
          PrivateHostedZoneName: "{{ dns_records.route53_hosted_zone_name }}"
          VPCId: "{{ network_exports.VPCId }}"
          VPCRegion: "{{ aws.region }}"
      tags:
        - create
