---

- name: Create Stack Builder AEM AWS resources stack
  hosts: all
  gather_facts: false
  connection: local

  tasks:
  
    - name: Create AWS resources stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ aws.resources.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../../templates/cloudformation/aws-resources.yaml"
