---
- name: AEM Nat-Gateway CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create Nat Gateway Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ nat_gateway.stack_name }}"
        state: present
        region: "{{ aws.region }}"
        disable_rollback: true
        template: "../../../cloudformation/network/nat-gateway.yaml"
        template_parameters:
          StackPrefix: "{{ stack_prefix }}"
          Ec2NatGatewayElasticIpAllocationIdParameter: "{{ nat_gateway.elastic_ip_allocation_id }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
            aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ nat_gateway.stack_name }}"
                --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ nat_gateway.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete Nat Gateway Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ nat_gateway.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
